server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  main:
    allow-circular-references: true
  task:
    execution:
      pool:
        core-size: 32
        max-size: 128

app:
  id: app2
  namespace: ns1
  env: sit
  mock: false
  cache: false
  retry: 2
